package com.java.entity.enums;

public enum PromptType {
    MATCH_CURRICULUM_VITAE,
    GENERATE_COVER_LETTER,
    IMPROVE_EXPERIENCE,
    IMPROVE_HARD_SKILLS,
    IMPROVE_SOFT_SKILLS,
    PARSE_CURRICULUM_VITAE,
    PARSE_JOB_DESCRIPTION
}