bot:
  name: AiCareerBoosterBot
  token: 6085118074:AAGajKqp3CZMHD_0q1W71yg3soFSwsojWAA
  text:
    model: gpt-3.5-turbo-0613
api:
  token: Bearer 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
  url:
    completions: https://api.openai.com/v1/chat/completions
